### ISSUE TITLE
你好，我是用react-native run-ios报错

### ISSUE THREAD

**Issue by JserJser** [930324291/React-Native-VehicleKeyBord#1]
Installing build/Build/Products/Debug-iphonesimulator/VehicleKeyBord.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/VehicleKeyBord.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by 930324291** [comment]
环境配置问题
